### ISSUE TITLE
Not displaying players in the Server Details

### ISSUE THREAD

**Issue by dinogomez** [Razzmatazzz/ValheimServerWarden#1]
![image](https://user-images.githubusercontent.com/41871666/108305376-cd8d3e00-71e4-11eb-9fd6-9e01fce77fa0.png)

**Comment by Razzmatazzz** [comment]
Are players connected when that screenshot was taken? Copying and pasting the details from the server log would be helpful.

**Comment by Razzmatazzz** [comment]
I haven't been able to reproduce this, and I haven't received any additional reports or information, so I'm closing the issue.
