### ISSUE TITLE
Set process valheim_server.exe with high priority on start

### ISSUE THREAD

**Issue by mockdot** [Razzmatazzz/ValheimServerWarden#12]
I am not completely sure how beneficial this really is, I have read suggestions and it feels (not sure if it's a placebo effect) as if the server ran a little smoother when manually setting the process to high priority rather than normal.

**Comment by Razzmatazzz** [comment]
I might add it as an option, but the MS docs [warn against it](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processpriorityclass?view=net-5.0#System_Diagnostics_ProcessPriorityClass_High):

> Use extreme care when specifying High for the process's priority class, because a high priority class application can use nearly all available processor time.

**Comment by Razzmatazzz** [comment]
Added in latest release.
