### ISSUE TITLE
Server won't start when using HTML formatting in server name

### ISSUE THREAD

**Issue by ScalaZen** [Razzmatazzz/ValheimServerWarden#13]
I just downloaded VSW after using only VSS for weeks.

I got an issue. I ran VSW added my server information and it all worked worked well, except it wouldn't change the name on the server list. So i closed it, opened tried opening it back up. Wont open. Restarted PC. Still wont open. Copied over the files from the Zip to replace it all and deleted the server .json. 

Now it launches but wont stay open. If i try selecting the path to SteamCMD it crashes. If i input all server details and start it. Crash.

**Comment by ScalaZen** [comment]
Upon further testing. I still cannot change SteamCMD's location it crashes each time.

If valheim_servers.json file is written it wont even launch VSW

**Comment by Razzmatazzz** [comment]
To change the name of the server from the main app server list, you have to double-click it. You can also right-click the server, select Details, select the Settings tab in the details window, and then change the server name (and other settings) from there.

For troubleshooting, please try to walk through the detailed steps of what you're doing that causes a crash.

When you say the app won't stay open, do you mean it closes on its own without any input from you, or that it closes when you do something in particular?

Are you pointing it to an existing installation of the dedicated server or trying to install the dedicated server?

At what point does it crash when you try to set the path to SteamCMD? As soon as you click the "SteamCMD Path" button, or after you select the folder in the dialog window that opens?

Sounds like something got messed up with your app settings. To clear out all the app settings, try this:

- Push Windows key+R
- Enter %userprofile%/appdata/local/ValheimServerWarden/ and push OK
- Delete all folders in the ValheimServerWarden folder

After that, you should be able to re-launch the app with default settings.

**Comment by ScalaZen** [comment]
![Screenshot 2021-02-28 220643](https://user-images.githubusercontent.com/79819727/109447249-42484f80-7a11-11eb-8af4-d858a544d578.png)

If i click that it crashes. If i launch it it crashes. 

Now i cleared the local data already, with my own troubleshooting, exactly like that path you gave me, and re-downloaded and installed 0.4.1.0. I seem to have been able to load VSW, add my server detail and run the server. Was even able to use the Discord WebHooks. We're getting somewhere.

Except im still having the issue above where i click "SteamCMD Path" and the entire client crashes.

**Comment by ScalaZen** [comment]
%userprofile%/appdata/local/ValheimServerWarden/ is actually saved under %userprofile%/appdata/local/Razzmatazzz

**Comment by Razzmatazzz** [comment]
Very strange that it's saving the app settings under Razzmatazzz... I'll have to look into that.

But I just pushed out a new release that should fix the SteamCMD crash.

**Comment by ScalaZen** [comment]
Downloading it now. Thank you.

**Comment by ScalaZen** [comment]
Great. Worked for me without crashing!

**Comment by ScalaZen** [comment]
Also idk if it affected the .json file causing the instant crashing and not opening properly, from my first post. What i had was a  "<color=AQUA>Dedicated Server</color>" on my Batch file prior to using VSW. I removed that and it launched without issues.

**Comment by Razzmatazzz** [comment]
Something in the server name might have been causing a parse error for the json. I also added in some error handling so the whole app doesn't crash out if it can't read the json file.

**Comment by ScalaZen** [comment]
https://github.com/Razzmatazzz/ValheimServerWarden/issues/13#issuecomment-787608286

> Something in the server name might have been causing a parse error for the json. I also added in some error handling so the whole app doesn't crash out if it can't read the json file.

Look right above :) that may be it.

Is the check on the 0.4.2.0?

**Comment by Razzmatazzz** [comment]
Yeah, the check is in the latest version. If there's an error, it won't load any of the saved servers. But at least it won't crash either.

**Comment by ScalaZen** [comment]
so the .json cannot support colors? I.e:  "<color=AQUA>Dedicated Server </ color >" 



 i gotta break up the /color bit, seems like github hides it from the post.

**Comment by Razzmatazzz** [comment]
I just set the name of the server to `<color=aqua>My Test Server</color>`.  Restarted the app and it launched just fine.

**Comment by Razzmatazzz** [comment]
Can attach your servers json file here with the color attribute set? Might want to remove the server password first.

**Comment by ScalaZen** [comment]
[valheim_servers.zip](https://github.com/Razzmatazzz/ValheimServerWarden/files/6061712/valheim_servers.zip)

**Comment by ScalaZen** [comment]
With that json it crashes. on Server Start.

**Comment by ScalaZen** [comment]
The second i take off `<color=aqua>Dedicatedr</color> Valheim Server` It works totally fine

**Comment by ScalaZen** [comment]
What's also weird, it keeps launching a fresh version of the server. Not sure why. the Directory is going to the same place. Theirs only 1 World in the worlds folder. But it makes the same world except fresh.

**Comment by Razzmatazzz** [comment]
I think I figured out what's causing the crash. Try disabling the option to create a server log file for now and that might solve the crashing on server start issue for you.

As for the second issue, you have a save folder configured in the server settings, but it re-creates the world each time you start the server? Have you confirmed that the save folder is actually saved (have to click the Save button at the bottom of the settings) by closing the app and re-opening it?

**Comment by ScalaZen** [comment]
Cant save logs, bummer. Let me try that.

Yes, in confirmed it saved, it actually wont properly save unless i click save. Close VSW, and re-open it. Then i see the changes.

**Comment by ScalaZen** [comment]
Update. 

The Logs being off let me adjust the color of my Server. 

~~I'm still having the issue where it creates a fresh server, instead of using my current world.~~

I figured it out, i didnt have the proper path to the Save Folder in the AppData/LocalLow/IronGate/Valheim Dir.

**Comment by ScalaZen** [comment]
So all Seems Resolved. Would still like to have Logs, No rush.
