### ISSUE TITLE
Auto update not working on 3.4.0

### ISSUE THREAD

**Issue by mockdot** [Razzmatazzz/ValheimServerWarden#14]
Noticed there were a few new updates and tried to auto update and received the following error:

3/1/2021 8:11:11 AM: Error checking for new version: Version string portion was too short or too long. (Parameter 'input')

I was also looking at what version I was running from the app but it's not possible to see, maybe a little about page might help follow the current version we are using. I was able to find it due to the zip folder having the version.

**Comment by Razzmatazzz** [comment]
Thanks for reporting. There was an issue with the latest release being named incorrectly, and that is now fixed. The latest versions also include more robust version checking, so a similar thing shouldn't be an issue in the future.

Also, the app's version number is displayed as the first log entry.
