### ISSUE TITLE
Automatically sending "save" console command on server stop

### ISSUE THREAD

**Issue by mockdot** [Razzmatazzz/ValheimServerWarden#15]
Not sure how possible this is. The Valheim team added a save console command to save the current progress for when you stop a server so you don't have to wait until the 20 minutes auto save. I've noticed duplicated items on certain server restarts, such as items being cooked after I had already got them.

**Comment by Razzmatazzz** [comment]
Unfortunately, not possible. The dedicated server window does not accept any command inputs while running.

Moreover, it's unnecessary in the context you're describing. When a server is given the signal to shut down, it triggers a world save.

**Comment by mockdot** [comment]
Ah, I would of guessed due to those things not saved that it did not trigger it, I guess that's a game bug that I should report to Iron Gate. Thanks!
