### ISSUE TITLE
VSW crashes when trying to set server path on version 0.4.6.0

### ISSUE THREAD

**Issue by Stumpfhoelzern** [Razzmatazzz/ValheimServerWarden#18]
Similar to #17 VSW crashes for me when: 

right click on server -> Details -> Settings -> open "Installation settings" -> click on "Server Path" (no matter what "Install Type" is selected. 

Windows gives following problem details:

Problemsignatur:
  Problemereignisname:	CLR20r3
  Problemsignatur 01:	QCO3LWOIUC45ICH1N43QXMQLZXWMWBYB
  Problemsignatur 02:	0.4.6.0
  Problemsignatur 03:	600b9eb8
  Problemsignatur 04:	System.Private.CoreLib
  Problemsignatur 05:	5.0.321.7212
  Problemsignatur 06:	90e4498f
  Problemsignatur 07:	5621
  Problemsignatur 08:	2a
  Problemsignatur 09:	System.ArgumentException
  Betriebsystemversion:	6.3.9600.2.0.0.272.7
  Gebietsschema-ID:	1031
  Zusatzinformation 1:	e5d5
  Zusatzinformation 2:	e5d5d40ffc68bcbc54a5cb5f5ff3782d
  Zusatzinformation 3:	30e6
  Zusatzinformation 4:	30e65915c41eb6d91e1439c815649cbd

Also many thanks for you great work, VSW is much nicer than having to fiddle with batch files.

**Comment by Razzmatazzz** [comment]
Latest release should fix this crash. Thanks for reporting.

**Comment by Stumpfhoelzern** [comment]
Wow 12 minutes reaction time, nice :-D.

After a clean install it is now working for me. Thanks for you quick work.

**Comment by Razzmatazzz** [comment]
In fairness, I was basically ready to do a release anyway so it was easy to include this fix as well.
