### ISSUE TITLE
Servers tab line items don't update to status as shown in the status bar

### ISSUE THREAD

**Issue by Xechorizo** [Razzmatazzz/ValheimServerWarden#19]
Title covers it mostly. Example:

![image](https://user-images.githubusercontent.com/14857131/110018455-89ba2e80-7ce4-11eb-8b8b-b4484626093e.png)

**Comment by Razzmatazzz** [comment]
Were you by chance editing some of the values in that main window before you started the server? If the grid is still in "edit" mode, it can't refresh.

Also applies if you start the server and then begin editing some of its values there before it finishes.

**Comment by Razzmatazzz** [comment]
I made some UI improvements that should prevent this in the latest version.
