### ISSUE TITLE
Problem with open Update Pages

### ISSUE THREAD

**Issue by tuvok81** [Razzmatazzz/ValheimServerWarden#2]
When i start the tool, i get a message.
![grafik](https://user-images.githubusercontent.com/30367063/108308445-0d85fe00-71b0-11eb-8c57-5fe2ccaed172.png)

i click on Yes
and they say that he can not find the data
![grafik](https://user-images.githubusercontent.com/30367063/108308510-242c5500-71b0-11eb-96ed-ff3705ef89ee.png)

**Comment by tuvok81** [comment]
Intresting, i have update the tool manual and he will also display this window

**Comment by Razzmatazzz** [comment]
Do you still have this problem after upgrading to the latest version?

**Comment by tuvok81** [comment]
i must wait, when you release a new version .. than i can say you :) .. the 0.2.1 is updated manual

**Comment by Razzmatazzz** [comment]
So
