### ISSUE TITLE
Add optional command to run on start (umod update, etc)

### ISSUE THREAD

**Issue by doublee313** [Razzmatazzz/ValheimServerWarden#26]
Would it be possible to add a startup command line to run commands? IE for umod update on start:

umod update game core apps extensions --patch-available --strict --validate --prerelease

Thank you.

**Comment by Razzmatazzz** [comment]
Probably possible, but I need to know the mechanics of how this works. Do you run the umod command before or after you start the server? Does the umod process have to finish before the server starts? Should this command run _every_ time before the server starts (e.g., when installing automatic server updates, when performing scheduled restarts), or just the first time the server is started after the VSW app is first launched?

**Comment by doublee313** [comment]
I'm no expert but here's the launcher.bat file:

@echo off
cls
:start

umod update game core apps extensions --patch-available --strict --validate --prerelease

@echo off
if %ERRORLEVEL% == 1 (echo Unable to update game, uMod core, or uMod apps.)
if %ERRORLEVEL% == 2 (echo No updated needed.)

echo Starting server...

valheim_server.exe -batchmode -nographics -name "Server" -port 2456 -world "Server" -password 00000 -public 1 -savedir "D:\Valheim\Saves"

This seems to run each time to check for the update.

**Comment by doublee313** [comment]
Maybe the "game" isn't needed....as yours has the auto update

Maybe make a Umod section where you can install the umod core and option to check for update on server start?

Rust Server Manager example: 

![image](https://user-images.githubusercontent.com/26212809/110212767-0d058c80-7e6b-11eb-8a1d-fdd2081991d6.png)

You can build on the plugin, etc later too.

I'm going to send you a donation in the next week for all your work. Awesome job.

**Comment by Razzmatazzz** [comment]
I have zero familiarity with umod, but am I correct in understanding that this command updates the game, umod, and any umod apps and extensions?

**Comment by doublee313** [comment]
Yes, that seems to be the formatting. I can test a beta if you need, etc. 

I'm using uMod and 4-5 plugins on my servers: Max Players, Auto Save, etc. It should be a huge thing soon :)

**Comment by Razzmatazzz** [comment]
Can you do windows key+R, paste in %userprofile%/.dotnet/tools/ and tell me if umod.exe is located in that folder?

**Comment by doublee313** [comment]
![image](https://user-images.githubusercontent.com/26212809/110216296-58746680-7e7c-11eb-8dcc-5ffa44c6c6b1.png)

:)

**Comment by Razzmatazzz** [comment]
When you install umod on a server, does it add another umod.exe to the server folder as well?

**Comment by doublee313** [comment]
No, it just creates a umod folder in the server folder with it's stuff. The umod.exe is where you had above I believe when you install the Umod installer.

Here's a search for umod in the folder:

![image](https://user-images.githubusercontent.com/26212809/110217234-fb2ee400-7e80-11eb-9d72-1fdb1c80d5b8.png)

**Comment by Razzmatazzz** [comment]
Gotcha. Thanks.

**Comment by Razzmatazzz** [comment]
I haven't installed uMod myself because installing via a powershell script with no uninstall option seems sketchy to me. But having looked at the documentation, the attached test build _might_ have some uMod functionality. Or it might make everything explode. If it successfully detects uMod installed on your PC, and you select "uMod" as the installation method, it should show a "uMod" tab. A button on that tab lets you do a manual update when the server isn't running. When the server is running, it should use uMod for all updates.

Or maybe it won't... hard to test since I don't have uMod installed myself. Try at your own risk.

Edited to change the test version to one that actually calls the uMod update command.

Edit: test version removed and new one attached below.

**Comment by doublee313** [comment]
I will test shortly. Thx. Driving home.

**Comment by Razzmatazzz** [comment]
[vsw-umod-test.zip](https://github.com/Razzmatazzz/ValheimServerWarden/files/6096326/vsw-umod-test.zip)
Use this version instead. It fixes some bugs.

One disadvantage of using uMod over SteamCMD is that there's no way I know of to check whether there's an update available without actually _doing_ an update. That means when the server is running, you can't just check for an update and then shut down the server to apply it. You have to shut down the server, then do the update command (which installs an update if available) and then start the server back up.

**Comment by doublee313** [comment]
I will now and report back. Thx

**Comment by doublee313** [comment]
I think the idea is, umod will update on start if need after the update. The game itself can be updated with SteamCMD, etc.

**Comment by Razzmatazzz** [comment]
Is that safe practice for uMod? uMod has its own command to update the game and uses the --patch-available flag to skip game updates "[if corresponding patched assemblies are not available](https://umod.org/guides/getting-started/agent#update)".

Based on my understanding, you can get yourself into trouble if you're using uMod and update the game outside of uMod. Am I incorrect in that understanding?

**Comment by doublee313** [comment]
I never update the game with umod just its files (Rust).

With Rust, after it SteamCmd update, we have to manually push it. This new
way seems nice to check on start just for the umod parts. Probably no need
for game update if that part refers to the actual Steam game files.

Waiting for a player to log and will test.

**Comment by doublee313** [comment]
Ok, it's up and running. Started ok. I will let it run for a bit and see. 

As for Umod updating the game, I would remove that part. Just the core, apps, extensions. 

Also, maybe add a button to install Umod to the server :)

**Comment by doublee313** [comment]
Im on Discord if you want to DM each other. Doublee#0313

**Comment by Razzmatazzz** [comment]
Preliminary uMod support added in 0.4.12.0.
