### ISSUE TITLE
Show display-friendly name of raids

### ISSUE THREAD

**Issue by mockdot** [Razzmatazzz/ValheimServerWarden#27]
![2021-03-08 15_01_01-Window](https://user-images.githubusercontent.com/10159765/110381486-20f1ef80-801f-11eb-9efd-8dc2bd8f9dfd.png)

![2021-03-08 15_00_44-Window](https://user-images.githubusercontent.com/10159765/110381491-218a8600-801f-11eb-9c0a-a6e72056609e.png)

Using 0.4.11.0

Was this giving a text name before? Or is this how it operates normally?

**Comment by Razzmatazzz** [comment]
That's how it's always worked. The name displayed is the name that appears in the raw server output and therefore _is_ the "actual" name.

**Comment by mockdot** [comment]
I am definitely going crazy lol, too much confinement. Any chance we could maybe convert that raw output to a variable and be able to modify it in the app? Would be nice to give it our own name or be able to translate it to other languages.

**Comment by Razzmatazzz** [comment]
Yeah, it's a possibility. I think the first step is collecting all the names of events. Pretty sure I recall seeing:
foresttrolls
army_elder
army_bonemass

I know I've experienced a surtling attack before, but I'm not sure what the server log name for it is. I also imagine there are "army_moder" and "army_yagluth" attacks, but unsure of their names. Is there also an "army_eikthyr" raid?

**Comment by mockdot** [comment]
I believe I found them all in the Wiki: https://valheim.fandom.com/wiki/Events

army_eikthyr
army_theelder
army_bonemass
army_moder
army_goblin

skeletons
blobs
foresttrolls
wolves
surtlings

I don't think I've seen an attack of wolves or blobs yet tho. Haven't killed Yagluth yet.

**Comment by Razzmatazzz** [comment]
Support for this is added in the latest release. Can modify all these default values plus add additional events as needed for future-proofing.
