### ISSUE TITLE
Startparameters

### ISSUE THREAD

**Issue by tempsn** [Razzmatazzz/ValheimServerWarden#28]
hello,
thank you for the great tool, my question:
Are there any startparameters or other methods to easy start/stop/restart the server?
I am trying to shutdown the server at certain times and looking for a safe and automatic way to stop the valheim server before the system shutdown.

**Comment by Razzmatazzz** [comment]
So, if I'm understanding correctly:

- The PC you're running the server on restarts on a predictable schedule
- You want to be able to automatically shut down the server before the PC shuts down
- You want to be able to automatically start the server when the PC starts back up

Is That all correct? The third part is the easiest. Just turn on the "Autostart" option for the server and set VSW to run when windows starts. On the first point, what's your use case that requires regularly rebooting the PC? That shouldn't really be necessary in most instances. I'm loathe to clutter up the interface with more options for extreme edge cases. But one option could be for VSW to monitor its own folder for the presence of a file (e.g., "shutdown.now"), and when it detects that file it will shut down all running servers. That way, you could automate creation of that file in the VSW folder before your computer shuts down and the VSW interface wouldn't be cluttered.

**Comment by tempsn** [comment]
> But one option could be for VSW to monitor its own folder for the presence of a file (e.g., "shutdown.now"), and when it detects that file it will shut down all running servers. That way, you could automate creation of that file in the VSW folder before your computer shuts down and the VSW interface wouldn't be cluttered.

Sounds great how hard would this be to implement?

**Comment by Razzmatazzz** [comment]
Not hard at all. I already have it working.

**Comment by tempsn** [comment]
So a future version will have this option?

**Comment by Razzmatazzz** [comment]
Yes, the future version I just released.

**Comment by tempsn** [comment]
Thank you works very well.
