### ISSUE TITLE
Prompt for already running servers

### ISSUE THREAD

**Issue by jim-022** [Razzmatazzz/ValheimServerWarden#33]
When I use the option to auto start server a prompt popup every time I start Warden app 
![image](https://user-images.githubusercontent.com/6962522/111900481-72e13f00-8a3b-11eb-989d-b9e7cce8b372.png)

If click 'no' the app will start the server just fine and it is managed by the warden app.

My target is to open Warden minimized on boot,

I am using Manual install option for the server and Auto Start option.
![image](https://user-images.githubusercontent.com/6962522/111900563-0286ed80-8a3c-11eb-8488-cdc29b67282a.png)

**Comment by Razzmatazzz** [comment]
Do you have another server running that isn't managed by VSW? That prompt appears when the app detects an already-running instance of valheim_server.exe on launch. If you don't think you have any servers running, click "yes" on that prompt and VSW will shut down any already-running servers.

**Comment by jim-022** [comment]
Did check all the processes also tested after reboot. Same result will do some further testing to check where is the root cause.

P.s.I will try debugging with the code from the repo if it still persists. (I thought it could be known issue.)

**Comment by Razzmatazzz** [comment]
[vsw-test.zip](https://github.com/Razzmatazzz/ValheimServerWarden/files/6178340/vsw-test.zip)
I think I found what the issue was. Try this test build and see if it works for you.

**Comment by jim-022** [comment]
That was quick , thanks I will give it a try.

**Comment by Razzmatazzz** [comment]
Fixed in latest version.
