### ISSUE TITLE
Automatic update isn't working

### ISSUE THREAD

**Issue by Razzmatazzz** [Razzmatazzz/ValheimServerWarden#34]
With the first game update pushed out since I added the auto update feature, it's not clear the automatic update isn't working. While I figure it out, you can still manually update by stopping your server, clicking the steamcmd button to the right of the discord webhooks button, and clicking Update.

**Comment by Razzmatazzz** [comment]
This might be fixed in the latest release. Leaving issue open for now in case it's not working for anyone.

**Comment by doublee313** [comment]
Auto update pushed when I installed this version.
