### ISSUE TITLE
Suggestion: More Messages on Discord Channel

### ISSUE THREAD

**Issue by tuvok81** [Razzmatazzz/ValheimServerWarden#35]
**Suggestion:**

It was nice, when you can replay this message on Discord channel 
(Optional enabeling on Server Settings, which Message are Replay on Discord)

"ServerName": No server update available.
"ServerName": Update complete.
"ServerName": Updating server to Version XXX.XX ...

I Miss the follow Message 
"Server is starting"
"Server is stopping" 
i see this on the tool but not on Discord

Optional is a good Part when you can make Variables.. than can the Peoples make his own Message for Replay to Discord

**Comment by Razzmatazzz** [comment]
Since there are already discord webhooks for the server finishing starting and finishing stopping, what's the utility of showing "Server is starting" and "Server is stopping" messages on discord? Just seems like it would be pointless spam.

**Comment by Razzmatazzz** [comment]
I added a webhook for when the server updates since that can be useful information (might want to check to make sure everything is still working after the update). I'm not going to add a "no update available" webhook because that isn't really useful information that needs to be pushed to discord.
