### ISSUE TITLE
Please add player character and world backups on a timer.

### ISSUE THREAD

**Issue by MokahTGS** [Razzmatazzz/ValheimServerWarden#42]
Please add the feature to save players characters on the server on a timed backup.  This feature is missing in the game and creates issues of players losing progress when playing on a server.

All players and world files should be saved on the server.  Currently only using mods makes this possible and they are not always reliable.

**Comment by Razzmatazzz** [comment]
I think Valheim Save Shield does what you're requesting.

**Comment by MokahTGS** [comment]
do we run this on the server or on the clients?

**Comment by Razzmatazzz** [comment]
Run it on the server to back up the world save, run it on the clients to back up the characters.

**Comment by MokahTGS** [comment]
It running on the server seems to be backing up the characters.

Would it not be better to have this as part of the server warden?

**Comment by Razzmatazzz** [comment]
I originally developed the save shield and then developed the server warden later. Everyone can use the save shield; not everyone needs the warden.
