### ISSUE TITLE
Discord Webhooks stopped working

### ISSUE THREAD

**Issue by nightchrono** [Razzmatazzz/ValheimServerWarden#47]
Starting on 01/09/23 Discord webhook stopped working with no changes to the webhook URL or changes to the application.

Latest attempt at restoring the webhook as it was:
1/18/2023 11:42:35 AM: SERVER: Error sending Discord webhook: The remote server returned an error: (400) Bad Request.

**Comment by JustGeorge34** [comment]
I have the same issue

**Comment by TheOzarkWizard** [comment]
I am also having this issue

**Comment by adrianoori** [comment]
Submitted pull request to resolve this issue.

**Comment by TheOzarkWizard** [comment]
^Someone, get this man a cookie!

**Comment by rokhead** [comment]
@adrianoori thanks for jumping on this.   There are other reports of this same error starting with the January API update.  The fix looks good.

**Comment by adrianoori** [comment]
It may be a while before @Razzmatazzz completes the PR, so I've made a build available here if anyone wants to use it ahead of the "official" release.

https://github.com/adrianoori/ValheimServerWarden/releases/tag/0.4.21.0

**Comment by Razzmatazzz** [comment]
Thank you for submitting the PR, @adrianoori ! New release:
https://github.com/Razzmatazzz/ValheimServerWarden/releases/tag/0.4.21.0
