### ISSUE TITLE
Discord webhooks repeating

### ISSUE THREAD

**Issue by HappyMolly** [Razzmatazzz/ValheimServerWarden#5]
# Version 0.3.0.0

Discord webhooks are repeating.

First the custom one is sent, and then the default one.

Custom: "{Player.Name} joined {Server.Name}."

Default: "{Player.Name} has entered the fray!"

![image](https://user-images.githubusercontent.com/66786107/108458629-52c03380-7275-11eb-8c37-d3432433d0b6.png)

**Comment by Razzmatazzz** [comment]
Ah yes, I started down one path of handling webhooks and then switched to another method and left some of the initial code behind. Fixed in the latest version. Thanks for reporting!
