### ISSUE TITLE
Server loses user counters after a while 

### ISSUE THREAD

**Issue by tuvok81** [Razzmatazzz/ValheimServerWarden#6]
The ServerManager lost the User Count ..
the User is Online Since 5hours and the Server lost the Information ca. 25min later
![grafik](https://user-images.githubusercontent.com/30367063/108607379-675d1280-73c0-11eb-992f-b5a7fe0a8148.png)
![grafik](https://user-images.githubusercontent.com/30367063/108607350-2107b380-73c0-11eb-9b27-eb9720c33a6c.png)

i have Connect to the Server but he will not show

**Comment by Razzmatazzz** [comment]
Please post the app log and the server log.

**Comment by tuvok81** [comment]
[Server.log.txt](https://github.com/Razzmatazzz/ValheimServerWarden/files/6016829/Server.log.txt)

**Comment by tuvok81** [comment]
Log near the Settings
-------------------------------
19.02.2021 06:23:12: Version 0.3.1.0
19.02.2021 06:23:36: Server tuvokTV Community Valheim starting...
19.02.2021 06:24:08: Server tuvokTV Community Valheim started.
19.02.2021 06:25:43: Server tuvokTV Community Valheim: player Sirtuvok (76561197961726274) connected
19.02.2021 06:26:25: Server tuvokTV Community Valheim: player Sirtuvok (76561197961726274) disconnected
19.02.2021 06:26:57: Server tuvokTV Community Valheim stopped.
19.02.2021 06:27:00: Server tuvokTV Community Valheim starting...
19.02.2021 06:27:31: Server tuvokTV Community Valheim started.
20.02.2021 12:19:48: Server tuvokTV Community Valheim: player Sirtuvok (76561197961726274) connected
20.02.2021 12:40:12: Server tuvokTV Community Valheim: player Sirtuvok (76561197961726274) disconnected
20.02.2021 14:30:10: Server tuvokTV Community Valheim: player Sirtuvok (76561197961726274) connected
20.02.2021 15:56:39: Server tuvokTV Community Valheim: player Sirtuvok (76561197961726274) died
20.02.2021 15:57:30: Server tuvokTV Community Valheim: random event army_theelder.
20.02.2021 15:59:27: Server tuvokTV Community Valheim: player Sirtuvok (76561197961726274) died
20.02.2021 16:02:29: Server tuvokTV Community Valheim: player Sirtuvok (76561197961726274) disconnected
20.02.2021 16:03:12: Server tuvokTV Community Valheim: player Scuritas (76561197961726274) connected
20.02.2021 16:25:41: Server tuvokTV Community Valheim: player Scuritas (76561197961726274) disconnected
20.02.2021 19:47:46: Server tuvokTV Community Valheim: random event army_theelder.
20.02.2021 21:15:35: Server tuvokTV Community Valheim: player Sirtuvok (76561197961726274) connected
20.02.2021 23:55:15: Server tuvokTV Community Valheim: player Sirtuvok (76561197961726274) disconnected

**Comment by tuvok81** [comment]
i think .. its a problem, when the Game is crashed .. the Game see not, that the player will logged out ..

**Comment by Razzmatazzz** [comment]
Yes, it's buggy. The server doesn't actually post messages saying that a player connected or disconnected, so I have to use less specific messages (or a combination of less specific messages) as a proxy for when players are connecting or disconnecting. That can lead to problems when unexpected things happen like a player crashes out instead of disconnecting.  I'll take a look at the logs and see if I can figure out a fix when I have time later today.

**Comment by Razzmatazzz** [comment]
I think the bug actually had to do with multiple players trying to connect around the same time. Latest release should fix it.
