### ISSUE TITLE
SteamCMD

### ISSUE THREAD

**Issue by dkdue** [Razzmatazzz/ValheimServerWarden#8]
Tip: Remove the server installation through Steam and change it to SteamCMD, those who use dedicated servers usually do not have Steam installed.

**Comment by Razzmatazzz** [comment]
I'm not removing anything. I might add a SteamCMD option eventually.

**Comment by dkdue** [comment]
ok it really is better steamcmd for servers but it is your project not mine it was just a suggestion or at least add option to install SteamCMD

**Comment by Razzmatazzz** [comment]
The "better" method to install the dedicated server is subjective.

I started with the regular Steam option because I figured someone who already has SteamCMD installed is less likely to need the extra help installing the dedicated server. Might add a SteamCMD option later.

**Comment by dkdue** [comment]
I understand it perfectly, I will look forward to if you decide to add SteamCMD later, the application has a lot of potential, another suggestion for later too, would be the possibility of installing plugins like umod from the application itself.

**Comment by Razzmatazzz** [comment]
To be clear, this app doesn't require that the game be installed via steam. You can install it via SteamCMD and then just point the app at valheim_server.exe and it'll work just fine.
